<?php

/**
 * Implements hook_menu().
 */
function sunflower_menu() {
  $items = array();
  $items['admin/sunflower'] = array(
    'title' => 'Sunflower',
    '#description' => 'Configure the Sunflower submission module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sunflower_admin_form'),
    'access arguments' => array('administer sunflower'),
    'file' => 'includes/admin.inc',
  );
  $items['admin/sunflower/delete'] = array(
    'title' => 'Sunflower Delete All Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sunflower_admin_delete_confirm_form'),
    'access arguments' => array('administer sunflower'),
    'file' => 'includes/admin.inc',
  );
  $items['sunflower'] = array(
    'title' => 'Sunflower Submission',
    'description' => 'Submission process for CSSR',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sunflower_landing_form'),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/landing.inc',
  );
  $items['sunflower/proposal/create'] = array(
    'title' => 'Sunflower Proposal Submission',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sunflower_proposal_form'),
    'access callback' => 'sunflower_proposal_create_access',
    'file' => 'includes/proposal.inc',
  );
  $items['sunflower/autocomplete/%'] = array(
    'page callback' => 'sunflower_presenter_autocomplete',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'file' => 'includes/autocomplete.inc',
  );
  $items['sunflower/proposal/edit/%'] = array(
    'title' => 'Sunflower Proposal Submission',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sunflower_proposal_form', 3),
    'access callback' => 'sunflower_proposal_edit_access',
    'access arguments' => array(3),
    'file' => 'includes/proposal.inc',
  );
  $items['sunflower/proposal/delete/%'] = array(
    'title' => 'Sunflower Proposal Delete Submission',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sunflower_proposal_delete_confirm_form', 3),
    'access callback' => 'sunflower_proposal_edit_access',
    'access arguments' => array(3),
    'file' => 'includes/delete.inc',
  );
  $items['sunflower/proposal/summary/%'] = array(
    'title' => 'Sunflower Proposal Summary',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sunflower_proposal_summary_form', 3),
    'access callback' => 'sunflower_proposal_summary_access',
    'access arguments' => array(3),
    'file' => 'includes/summary.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function sunflower_permission() {
  return array(
    'administer sunflower' => array(
      'title' => 'Configure the Sunflower module',
    ),
  );
}

function sunflower_proposal_create_access() {
  module_load_include('inc', 'sunflower', 'includes/utilities');
  return (user_access('administer sunflower')) || (sunflower_is_valid_submitter() && sunflower_is_submission_open());
}

function sunflower_proposal_edit_access($proposal_id) {
  module_load_include('inc', 'sunflower', 'includes/utilities');
  module_load_include('inc', 'sunflower', 'includes/db');
  global $user;
  $submitter = sunflower_retrieve_submitter_uid($proposal_id);
  // Non-existing proposal.
  if (!$submitter) {
    return FALSE;
  }
  if (user_access('administer sunflower')) {
    return TRUE;
  }
  else {
    return sunflower_is_valid_submitter() && sunflower_is_submission_open() && ($submitter == $user->uid);
  }
}

function sunflower_proposal_summary_access($proposal_id) {
  module_load_include('inc', 'sunflower', 'includes/utilities');
  module_load_include('inc', 'sunflower', 'includes/db');
  global $user;
  $submitter = sunflower_retrieve_submitter_uid($proposal_id);
  // Non-existing proposal.
  if (!$submitter) {
    return FALSE;
  }
  if (user_access('administer sunflower')) {
    return TRUE;
  }
  else {
    return sunflower_is_valid_submitter() && ($submitter == $user->uid);
  }
}